name:                a-dark-room
version:             0.1.0.0
github:              "jordangedney/adarkroom-port"
license:             MPL-2.0
author:              "Jordan Gedney"
maintainer:          "jordangedney@gmail.com"
copyright:           "2020 Jordan Gedney"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jordangedney/adarkroom-port>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-orphans
  - -Wmissing-signatures
  dependencies:
  - brick
  - vty
  - lens
  - yaml

executables:
  a-dark-room-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - a-dark-room
    - brick
    - vty
